# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    ibm_profile: "#{source_dir}"
  repositories:
    facts:        'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision:    'git://github.com/puppetlabs/provision.git'
    easy_type:    'https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/enterprisemodules/easy_type_src.git'
    iib_install:  'https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/enterprisemodules/iib_install.git'

    iib_config:   'https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/enterprisemodules/iib_config.git'
    mq_install:   'https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/enterprisemodules/mq_install.git'
    mq_config:    'https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/enterprisemodules/mq_config.git'

  forge_modules:
    stdlib:                 puppetlabs/stdlib
    echo:                   ipcrm/echo
    archive:                puppet/archive
    augeas_core:            puppetlabs-augeas_core
    augeasproviders_core:   herculesteam-augeasproviders_core
    augeasproviders_sysctl: herculesteam-augeasproviders_sysctl
    limits:                 saz/limits
    firewall:               puppetlabs-firewall
    firewalld:              puppet-firewalld
    sleep:                  fiddyspence-sleep
    dirtree:                AlexCline-dirtree
