# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    ibm_profile: "#{source_dir}"
  repositories:
    facts:        'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision:    'git://github.com/puppetlabs/provision.git'
  forge_modules:
    easy_type:              enterprisemodules/easy_type
    iib_install:            enterprisemodules/iib_install
    iib_config:             enterprisemodules/iib_config
    mq_install:             enterprisemodules/mq_install
    mq_config:              enterprisemodules/mq_config
    stdlib:                 puppetlabs/stdlib
    echo:                   ipcrm/echo
    archive:                puppet/archive
    augeas_core:            puppetlabs-augeas_core
    augeasproviders_core:   herculesteam-augeasproviders_core
    augeasproviders_sysctl: herculesteam-augeasproviders_sysctl
    limits:                 saz/limits
    firewall:               puppetlabs-firewall
    firewalld:              puppet-firewalld
    sleep:                  fiddyspence-sleep
    dirtree:                AlexCline-dirtree
