---
require: rubocop-performance
AllCops:
  NewCops: enable

  Include:
  - "**/*.rb"
  Exclude:
  - "**/preamble.rb"
  - "**/.identity.rb"
  - "**/jwt.rb"
  - spec/**/*.rb
  - "**/*.rake"
  - "**/*.task"
  - "**/Gemfile"
  - "**/Rakefile"
  - "**/Guardfile"
  - "**/Vagrantfile"
  - lib/1.8.7/csv.rb
  - pkg/**/*
  - bin/*
Layout/HeredocIndentation:
  Enabled: false
Security/Eval:
  Enabled: false
Layout/LineLength:
  Max: 200
Naming/AccessorMethodName:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Layout/DotPosition:
  EnforcedStyle: trailing
Style/NumericPredicate:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: hash_rockets
Style/SignalException:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Naming/ClassAndModuleCamelCase:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Performance/RegexpMatch:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
