#++--++
#--++--
class ibm_profile::iib_machine(
  Optional[String] $before_sysctl = undef,
  Optional[String] $before_limits = undef,
  Optional[String] $before_groups_and_users = undef,
  Optional[String] $before_packages = undef,
  Optional[String] $before_firewall = undef,
  Optional[String] $before_software = undef,
  Optional[String] $before_broker_setup = undef,
  Optional[String] $before_server_setup = undef,
  Optional[String] $before_deployments = undef,
  Optional[String] $before_autostart = undef,
  Optional[String] $sysctl = undef,
  Optional[String] $limits = undef,
  Optional[String] $groups_and_users = undef,
  Optional[String] $packages = undef,
  Optional[String] $firewall = undef,
  Optional[String] $software = undef,
  Optional[String] $server_setup = undef,
  Optional[String] $broker_setup = undef,
  Optional[String] $deployments = undef,
  Optional[String] $autostart = undef,
  Optional[String] $after_sysctl = undef,
  Optional[String] $after_limits = undef,
  Optional[String] $after_groups_and_users = undef,
  Optional[String] $after_packages = undef,
  Optional[String] $after_firewall = undef,
  Optional[String] $after_software = undef,
  Optional[String] $after_broker_setup = undef,
  Optional[String] $after_server_setup = undef,
  Optional[String] $after_deployments = undef,
  Optional[String] $after_autostart = undef,
) inherits ibm_profile {
  easy_type::staged_contain([
    'ibm_profile::iib_machine::sysctl',
    'ibm_profile::iib_machine::limits',
    'ibm_profile::iib_machine::groups_and_users',
    'ibm_profile::iib_machine::packages',
    'ibm_profile::iib_machine::firewall',
    'ibm_profile::iib_machine::software',
    'ibm_profile::iib_machine::broker_setup',
    'ibm_profile::iib_machine::server_setup',
    'ibm_profile::iib_machine::deployments',
    'ibm_profile::iib_machine::autostart',
  ])
}
